project_id = "glpwshjvtofkxcmsiuts"

[functions.image-to-pdf]
verify_jwt = false

[functions.split-pdf]
verify_jwt = false

[functions.merge-pdf]
verify_jwt = false

[functions.compress-pdf]
verify_jwt = false
